### ISSUE TITLE
Calling fetch returns error

### ISSUE THREAD

**Issue by MineDrum** [JohnAlbin/storybook-addon-fetch-mock#7]
I'm using Vue 3, Storybook 6, Vite 3, Typescript
Anytime I make a fetch request the following error appears: 
`server.js:16563 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.normalizeRequest (server.js:16563:15)
    at FetchMock$1.fetchHandler (server.js:16759:41)
    at Menu.vue:131:27`

My code works outside of storybook and everything else besides the fetch request works inside my story. I've tried setting up fetchMock in the story and in preview.js

**Comment by JohnAlbin** [comment]
I used Vue once a few years ago and never with Storybook. But I whipped up a little example over the weekend to make sure this addon works with Vue and I didn't have any issues.

Here's the example repo: https://github.com/JohnAlbin/storybook-addon-fetch-mock-vue-example

If you still can't fix the error after looking at the example, can you post more details about your code? I suspect it might be that your components aren't handling the "fetch hasn't returned yet" scenario, but I'm not positive.
